### ISSUE TITLE
Gatsby 4.0.0 support

### ISSUE THREAD

**Issue by tansongchen** [alvis/gatsby-source-notion#3]
Thank you so much for making this plugin! I noticed that recently Gatsby released version 4.0.0 (https://github.com/gatsbyjs/gatsby/releases/tag/gatsby%404.0.0), could you please check if this plugin works with 4.0.0 and bump the version? I would be happy to contribute if you found any gaps.

**Comment by alvis** [comment]
@tansongchen I have released 1.0.5 for Gatsby 4 support. Check it out! :)

**Comment by tansongchen** [comment]
Great, will try
