### ISSUE TITLE
Add Image Support (now possible)

### ISSUE THREAD

**Issue by nicam** [alvis/gatsby-source-notion#4]
Notion has now added image support :) 

https://www.saurish.com/blog/notion-api-images

**Comment by alvis** [comment]
Yes. Time to work on it! 👍🏼

**Comment by conradlin** [comment]
How's the progress on this? Living this plugin, working very well.

**Comment by mitchmalone** [comment]
Hey @alvis any update on this? Really excited to see this.

**Comment by alvis** [comment]
Hi @mitchmalone @tansongchen! Sorry for the delay due to work.
But the good news is image support is now available on v1.2 & you can check out an example from the [e2e](../tree/master/e2e) folder 😃

**Comment by tansongchen** [comment]
Thanks for your super fast response! Upgraded to v1.2 and it worked like a charm
