### ISSUE TITLE
Page cover is missing in page property

### ISSUE THREAD

**Issue by tansongchen** [alvis/gatsby-source-notion#5]
I am currently using this plugin to retrieve a notion database in which each children page has a cover image that I wish to display on my website. I tried

```graphql
query MyQuery {
  allNotionDatabase {
    nodes {
      title
      childrenNotionPage {
        title
        childrenMdx {
          frontmatter {
            cover
          }
        }
      }
    }
  }
}
```

but this did not work.

**Comment by alvis** [comment]
The current version of the plugin relies on an easier version of Notion API, which didn't include properties such as page cover and icon. But I do think it's time to upgrade it. Let me try to work on it over the weekend. Thanks for reporting :)

**Comment by tansongchen** [comment]
I made a pr for this #6

**Comment by alvis** [comment]
@tansongchen Sorry for the belated update.
This library has undergone a big upgrade & cover image and icon are now supported since 1.1 :)

**Comment by tansongchen** [comment]
Great! Will try

**Comment by tansongchen** [comment]
Works like a charm!
